In [24]:
import numpy as np 

### The Basics

In [31]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [27]:
# Get Dimentions
a.ndim

1

In [28]:
# Get Shape
b.shape

(2, 3)

In [29]:
# Get Type
a.dtype

dtype('int16')

In [32]:
# Get Size
a.itemsize

4

In [34]:
# Get total size
a.nbytes

12