In [24]:
import numpy as np 

### The Basics

In [31]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [27]:
# Get Dimentions
a.ndim

1

In [28]:
# Get Shape
b.shape

(2, 3)

In [29]:
# Get Type
a.dtype

dtype('int16')

In [32]:
# Get Size
a.itemsize

4

In [34]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns,etc

In [35]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
# Get a specific element [r, c]
a[1,5]

13

In [40]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [42]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [45]:
a[1,5]=20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-d example

In [48]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)